name: Update Minesweeper Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.repository_owner }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install svgwrite requests
      
      - name: Create directories
        run: |
          mkdir -p assets
          mkdir -p scripts
          
      - name: Write style.css
        run: echo "${{ secrets.STYLE_CSS }}" > assets/styles.css
        
      - name: Generate Minesweeper SVG
        run: python scripts/generate_minesweeper.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add minesweeper.svg
          git add assets/styles.css
          git commit -m "auto: update minesweeper.svg"
          git push
