name: Update Minesweeper Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.repository_owner }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite requests
      
      - name: Set up environment
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
          
      - name: Create directories
        run: |
          mkdir -p assets
          mkdir -p scripts
          
      - name: Write style.css
        run: echo "${{ secrets.STYLE_CSS }}" > assets/styles.css
        
      - name: Generate Minesweeper SVG
        run: |
          echo "开始生成扫雷图..."
          # 设置工作目录为仓库根目录
          cd ${{ github.workspace }}
          python scripts/generate_minesweeper.py
          echo "SVG生成完成"
          ls -l minesweeper.svg
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto: update minesweeper.svg"
          file_pattern: |
            minesweeper.svg
            assets/styles.css
          branch: main
