name: Update Minesweeper Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.repository_owner }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite requests
      
      - name: Set up environment
        run: |
          echo "GH_TOKEN=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          
      - name: Create directories
        run: |
          mkdir -p assets
          mkdir -p scripts
          
      - name: Write style.css
        run: echo "${{ secrets.STYLE_CSS }}" > assets/styles.css
        
      - name: Generate Minesweeper SVG
        run: |
          python scripts/generate_minesweeper.py
          ls -l minesweeper.svg
          ls -l minesweeper.json
          
      - name: Generate Minesweeper Game HTML
        run: |
          # 创建HTML文件（使用上面的完整HTML内容）
          cat > minesweeper_game.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <!-- 上面提供的完整HTML内容 -->
          </head>
          <body>
              <!-- 上面提供的完整HTML内容 -->
          </body>
          </html>
          EOF
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto: update minesweeper files"
          file_pattern: |
            minesweeper.svg
            minesweeper.json
            assets/styles.css
            minesweeper_game.html
          branch: main
