name: Update Minesweeper Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.repository_owner }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install svgwrite requests
      
      - name: Set up environment
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
          
      - name: Generate Minesweeper SVG
        run: |
          mkdir -p assets
          echo "${{ secrets.STYLE_CSS }}" > assets/styles.css
          python -m scripts.generate_minesweeper
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto: update minesweeper.svg"
          file_pattern: |
            minesweeper.svg
            assets/styles.css
